services:
  db:
    image: postgres:16
    container_name: securespace-db
    restart: unless-stopped
    environment:
     TZ: Europe/Kyiv
    PGTZ: Europe/Kyiv
      POSTGRES_USER: securespace
      POSTGRES_PASSWORD: securespace_pass
      POSTGRES_DB: securespace
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U securespace -d securespace"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: securespace-api
    restart: unless-stopped
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: securespace
      POSTGRES_PASSWORD: securespace_pass
      POSTGRES_DB: securespace
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run migration:run && npm run start"

volumes:
  pgdata:
